export default [
  {id:"1",icon:'tui-icon ti-chinese-lantern',label:'tuiIntro',title:'TechUI简介',parentId:null,isParent:false,order:1},
  
  {id:"2",icon:'tui-icon ti-atom-alt',label:'basicModule',title:'基础模块',parentId:null,isParent:true,order:2},
    {id:"2A",label:'tuiServiceDemo',title:'tService',parentId:"2",isParent:false,order:1},
    {id:"2B",label:'backgroundDemo',title:'背景',parentId:"2",isParent:false,order:2},
    {id:"2C",label:'iconsDemo',title:'内置图标',parentId:"2",isParent:false,order:3},
    {id:"2D",label:'audioDemo',title:'提示音',parentId:"2",isParent:false,order:4},
    {id:"2E",label:'i18nDemo',title:'多语言',parentId:"2",isParent:false,order:5},
    {id:"2F",label:'themeDemo',title:'主题预览',parentId:"2",isParent:false,order:6},

  {id:"3",icon:'tui-icon ti-component',label:'base',title:'Base组件库',parentId:null,isParent:true,order:3},

  {id:"3B",label:'common',title:'常用组件',parentId:"3",isParent:true,order:3},
    {id:"3B1",label:'buttonDemo',title:'按钮',parentId:"3B",isParent:false,order:1},
    {id:"3B2",label:'inputDemo',title:'输入框',keepAlive:true,parentId:"3B",isParent:false,order:2},
    {id:"3B3",label:'timePickerNativeDemo',title:'时间选择器(原生)',parentId:"3B",isParent:false,order:3},
    {id:"3B4",label:'selectDemo',title:'下拉框',parentId:"3B",isParent:false,order:4},
    {id:"3B5",label:'selectNativeDemo',title:'下拉框(原生)',parentId:"3B",isParent:false,order:5},
    {id:"3B6",label:'toggleDemo',title:'切换按钮',parentId:"3B",isParent:false,order:6},
    {id:"3B7",label:'checkboxDemo',title:'复选框',parentId:"3B",isParent:false,order:7},
    {id:"3B8",label:'radioDemo',title:'单选框',parentId:"3B",isParent:false,order:8},
    {id:"3B9",label:'tagDemo',title:'标记',parentId:"3B",isParent:false,order:7},
    {id:"3B10",label:'formDemo',title:'表单',keepAlive:true,parentId:"3B",isParent:false,order:10},

  {id:"3C",label:'container',title:'容器组件',parentId:"3",isParent:true,order:4},
    {id:"3C1",label:'typedDemo',title:'类型面板',parentId:"3C",isParent:false,order:1},
    {id:"3C2",label:'dialogDemo',title:'弹出框',parentId:"3C",isParent:false,order:2},
    {id:"3C3",label:'dialogNativeDemo',title:'弹出框-原生',parentId:"3C",isParent:false,order:3},
    {id:"3C4",label:'drawerDemo',title:'抽屉弹出框',parentId:"3C",isParent:false,order:4},
    {id:"3C5",label:'carouselDemo',title:'轮播',parentId:"3C",isParent:false,order:5},
    {id:"3C6",label:'accordionDemo',title:'手风琴组件',parentId:"3C",isParent:false,order:6},
    // {id:"3C8",label:'loaderPanelDemo',title:'模块加载面板',parentId:"3C",isParent:false,order:8},
    
  {id:"3D",label:'prompt',title:'提醒提示',parentId:"3",isParent:true,order:5},
    {id:"3D1",label:'attentionDemo',title:'提醒组件',parentId:"3D",isParent:false,order:1},
    {id:"3D2",label:'popTipDemo',title:'弹出提示',parentId:"3D",isParent:false,order:2},
    {id:"3D3",label:'curTipDemo',title:'光标提示',parentId:"3D",isParent:false,order:3},
    {id:"3D4",label:'textTipDemo',title:'文字提示',parentId:"3D",isParent:false,order:4},
    {id:"3D5",label:'emptyDemo',title:'空组件',parentId:"3D",isParent:false,order:5},
    {id:"3D6",label:'loadingDemo',title:'加载',parentId:"3D",isParent:false,order:6},
    {id:"3D7",label:'rollingNotificationDemo',title:'滚动通知',parentId:"3D",isParent:false,order:7},

  {id:"3E",label:'dataVisual',title:'数据组件',parentId:"3",isParent:true,order:6},
    {id:"3E1",label:'calendarDemo',title:'日历',parentId:"3E",isParent:false,order:1},
    {id:"3E2",label:'digitalFlipDemo',title:'数字翻牌',parentId:"3E",isParent:false,order:2},
    {id:"3E3",label:'digitalRollingDemo',title:'数字滚动',parentId:"3E",isParent:false,order:3},
    {id:"3E4",label:'timelineDemo',title:'时间线',parentId:"3E",isParent:false,order:4},
    {id:"3E5",label:'progressDemo',title:'进度组件',parentId:"3E",isParent:false,order:5},
    {id:"3E6",label:'progressPoolDemo',title:'进度池',parentId:"3E",isParent:false,order:6},
    {id:"3E7",label:'rollingProgressDemo',title:'滚动进度条',parentId:"3E",isParent:false,order:7},
    {id:"3E8",label:'rollingTableDemo',title:'滚动表格',parentId:"3E",isParent:false,order:8},

  {id:"3F",label:'navigation',title:'导航组件',parentId:"3",isParent:true,order:7},
    {id:"3F1",label:'navDemo',title:'导航',parentId:"3F",isParent:false,order:1},
    {id:"3F2",label:'treeDemo',title:'树形',parentId:"3F",isParent:false,order:2},
    {id:"3F3",label:'rollingNavIconDemo',title:'滚动图标导航',parentId:"3F",isParent:false,order:3},
    {id:"3F4",label:'rollingNavTabsDemo',title:'滚动标签导航',parentId:"3F",isParent:false,order:4},
    {id:"3F5",label:'menuDemo',title:'菜单',parentId:"3F",isParent:false,order:5},
    {id:"3F6",label:'stepsDemo',title:'步骤条',parentId:"3F",isParent:false,order:6},
    {id:"3F7",label:'tabDemo',title:'标签页',keepAlive:true,parentId:"3F",isParent:false,order:7},
    {id:"3F8",label:'tabScrollDemo',title:'标签页(滚动)',parentId:"3F",isParent:false,order:8},
    {id:"3F9",label:'stepScrollerDemo',title:'步进滚动器',parentId:"3F",isParent:false,order:9},
    {id:"3F10",label:'virtualScrollerDemo',title:'虚拟滚动器',parentId:"3F",isParent:false,order:10},

  {id:"3G",label:'rollingGroup',title:'滚动组件',parentId:"3",isParent:true,order:8},
    {id:"3G1",label:'rollingBaseDemo',title:'滚动基础',parentId:"3G",isParent:false,order:1},
    {id:"3G2",label:'rollingNavIconDemo',title:'滚动图标导航',parentId:"3G",isParent:false,order:2},
    {id:"3G3",label:'rollingNavTabsDemo',title:'滚动标签导航',parentId:"3G",isParent:false,order:3},
    {id:"3G4",label:'rollingNotificationDemo',title:'滚动通知',parentId:"3G",isParent:false,order:4},
    {id:"3G5",label:'rollingProgressDemo',title:'滚动进度条',parentId:"3G",isParent:false,order:5},
    {id:"3G6",label:'rollingTableDemo',title:'滚动表格',parentId:"3G",isParent:false,order:6},
    {id:"3G7",label:'stepScrollerDemo',title:'步进滚动器',parentId:"3G",isParent:false,order:7},
    {id:"3G8",label:'virtualScrollerDemo',title:'虚拟滚动器',parentId:"3G",isParent:false,order:8},

  {id:"3H",label:'layout',title:'布局组件',parentId:"3",isParent:true,order:9},
    {id:"3H1",label:'rowColDemo',title:'行列',parentId:"3H",isParent:false,order:7},
    {id:"3H2",label:'gridDemo',title:'网格',parentId:"3H",isParent:false,order:7},
    
  {id:"3I",label:'other',title:'其他组件',parentId:"3",isParent:true,order:9},
    {id:"3I1",label:'loginDemo',title:'登录',keepAlive:true,parentId:"3I",isParent:false,order:1},
    {id:"3I2",label:'textGradientDemo',title:'文字渐变',parentId:"3I",isParent:false,order:2},
    {id:"3I3",label:'crosshairDemo',title:'准星',parentId:"3I",isParent:false,order:3},
    {id:"3I4",label:'tuiIconLogoDemo',title:'Logo',parentId:"3I",isParent:false,order:4},

  {id:"5",icon:"tui-icon ti-crown",label:'advanceCompt',title:'高级组件',parentId:null,isParent:true,order:5},
    {id:"5A",label:'advIntro',title:'高级组件介绍',parentId:"5",isParent:false,order:1},
    {id:"5B",label:'adaptiveDemo',title:'适配面板',parentId:"5",isParent:false,order:1},
    {id:"5C",label:'panicAlertDemo',title:'恐慌告警',parentId:"5",isParent:false,order:2},
    {id:"5D",label:'t3DPanel',title:'3D面板',parentId:"5",isParent:false,order:3},
    {id:"5E",label:'bar3DDemo',title:'3D柱图',parentId:"5",isParent:false,order:6},
    {id:"5F",label:'pie3DDemo',title:'3D饼图',parentId:"5",isParent:false,order:7},
    {id:"5G",label:'echartsCom',title:'TuiEcharts',icon:'tui-icon ti-chart-bar',parentId:"5",isParent:true,order:8},
      {id:"5G1",label:'echartsMix3D',title:'Mix3D',parentId:"5G",isParent:false,order:1},
      {id:"5G2",label:'echartsPie',title:'Pie',parentId:"5G",isParent:false,order:2},

  {id:"10",icon:'tui-icon ti-palette',label:'colors',title:'配色表',parentId:null,isParent:true,order:10},
    {id:"10A",label:'colorV1',title:'颜色表基础',parentId:"10",isParent:false,order:1},
    {id:"10B",label:'colorV2',title:'颜色表扩展',parentId:"10",isParent:false,order:2},
    {id:"10C",label:'colorMatch',title:'颜色匹配',parentId:"10",isParent:false,order:3},

];