<script setup>
import { $c } from "@techui/colors";
import { onMounted, reactive } from 'vue';
const state=reactive({
  buttonApperAct:"Base",
  buttonApperOpt:[ "Base", "A1", "A2", "A3", "B1", "Group"],
  radioCfg:{ appearance:"button",  defaultIcon:false, },
  showActiveGroup:false,
  boolOpt:[
    {label:"是",value:true},
    {label:"否",value:false},
  ],

  groupObj:{
    Base:[
      {label:"Base",children:[
        {label:"Normal",common:{},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul5},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-cog",label:"With icon"},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        {label:"Active",className:"is-active",common:{},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
      ]},
      {label:"Plain",children:[
        {label:"Normal",common:{plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
      ]},
      {label:"Round",children:[
        {label:"Normal",common:{round:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.orl4,$c.pul5]},
          {type:"divider"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{round:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        {label:"Plain",common:{plain:true,round:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
        {label:"Disabled",common:{plain:true,round:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
      ]},
      {label:"Circle",children:[
        {label:"Normal",common:{icon:"tui-icon ti-star",circle:true},children:[
          {type:"default",},
          {type:"invert"},
          {type:"focus",},
          {type:"info",},
          {type:"primary",},
          {type:"success",},
          {type:"warning",},
          {type:"danger",},
          {type:"emphasis",},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{icon:"tui-icon ti-star",circle:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        {label:"Plain",common:{icon:"tui-icon ti-star",circle:true,plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        {label:"Disabled",common:{icon:"tui-icon ti-star",circle:true,plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
      ]},
      {label:"Link",children:[
        {label:"Normal",common:{link:true},children:[
          {type:"default"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{link:true,disabled:true},children:[
          {type:"default"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
      ]},
      {label:"Text",children:[
        {label:"Normal",common:{text:true},children:[
          {type:"default"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{text:true,disabled:true},children:[
          {type:"default"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          
        ]},
        {label:"Background always on",common:{text:true,textWithBG:true},children:[
          {type:"default"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled background always on",common:{text:true,disabled:true,textWithBG:true},children:[
          {type:"default"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          
        ]},
        
        
      ]},
    ],
    A1:[
      {label:"A1A",children:[
        {label:"Normal",common:{appearance:"A1"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:0},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:0},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:0},
        ]},
        {label:"Disabled",common:{appearance:"A1",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A1"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
        
        {label:"Plain Normal",common:{appearance:"A1",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:0},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:0},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:0},
        ]},
        {label:"Plain Disabled",common:{appearance:"A1",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:[$c.pul1,$c.pul5]},
        ]},
      ]},
      {label:"A1B",children:[
        {label:"Normal",common:{appearance:"A1",decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success",decoDirection:"bl"},
          {type:"warning",decoDirection:"tl"},
          {type:"danger",decoDirection:"tr"},
          {type:"emphasis",decoDirection:"tr"},
          {label:"Custom",customColor:$c.pul4,borderRadius:0},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoOffset:6,borderRadius:0},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:6,borderRadius:0},
          {type:"primary",size:"large",label:"large",decoSize:6,borderRadius:0},
          {type:"primary",size:"small",label:"small",decoSize:2,borderRadius:0},
        ]},
        {label:"Disabled",common:{appearance:"A1",decoType:"B",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A1",decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A1",plain:true,decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success",decoDirection:"bl"},
          {type:"warning",decoDirection:"tl"},
          {type:"danger",decoDirection:"tr"},
          {type:"emphasis",decoDirection:"tr"},
          {label:"Custom",decoDirection:"tr",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoOffset:6,borderRadius:0},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:6,borderRadius:0},
          {type:"primary",size:"large",label:"large",decoSize:5,borderRadius:0},
          {type:"primary",size:"small",label:"small",decoSize:2,borderRadius:0},
        ]},
        {label:"Plain Disabled",common:{appearance:"A1",plain:true,decoType:"B",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A1C",children:[
        {label:"Normal",common:{appearance:"A1",decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {type:"primary",label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:3},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:6},
          {type:"primary",size:"large",label:"large",decoSize:12},
          {type:"primary",size:"small",label:"small",decoSize:8},
        ]},
        {label:"Disabled",common:{appearance:"A1",decoType:"C",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A1",decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A1",plain:true,decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:3},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:4},
          {type:"primary",size:"large",label:"large",decoSize:12},
          {type:"primary",size:"small",label:"small",decoSize:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A1",plain:true,decoType:"C",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

      ]},
    ],
    A2:[
      {label:"A2B",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"B",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        
        {label:"Plain Normal",common:{appearance:"A2",decoType:"B",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"B",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2C",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"C",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"C",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"C",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2D",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"D"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"D",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"D"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"D",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"D",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2E",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"E"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"E",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"E"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"E",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"E",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2F",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"F"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"F",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"F"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"F",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"F",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
        ]},
      ]},
      {label:"A2G",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"G"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"G",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"G"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"G",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"G",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2H",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"H"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"H",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"H"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"H",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"H",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2I",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"I"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"I",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"I"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"I",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"I",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"default"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A2J",children:[
        {label:"Normal",common:{appearance:"A2",decoType:"J"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Disabled",common:{appearance:"A2",decoType:"J",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Active",className:"is-active",common:{appearance:"A2",decoType:"J"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      
        {label:"Plain Normal",common:{appearance:"A2",decoType:"J",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoThickness:5},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoThickness:2},
          {type:"primary",size:"large",label:"large",borderRadius:50},
          {type:"primary",size:"small",label:"small",borderRadius:8},
        ]},
        {label:"Plain Disabled",common:{appearance:"A2",decoType:"J",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
    ],
    A3:[
      {label:"A3A",children:[
        {label:"Normal",common:{appearance:"A3"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4,borderRadius:50},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:10},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:50},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:0},
        ]},
        {label:"Disabled",common:{appearance:"A3",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A3"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        
        {label:"Plain Normal",common:{appearance:"A3",plain:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:10},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:50},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:0},
        ]},
        {label:"Plain Disabled",common:{appearance:"A3",plain:true,disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A3B",children:[
        {label:"Normal",common:{appearance:"A3",decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {type:"primary",label:"Custom",customColor:$c.pul4,borderRadius:50},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:10},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:50},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:0},
        ]},
        {label:"Disabled",common:{appearance:"A3",decoType:"B",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A3",decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A3",plain:true,decoType:"B"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:10},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:50},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:0},
        ]},
        {label:"Plain Disabled",common:{appearance:"A3",plain:true,decoType:"B",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
      {label:"A3C",children:[
        {label:"Normal",common:{appearance:"A3",decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {type:"primary",label:"Custom",customColor:$c.pul4,borderRadius:50},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",borderRadius:10},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",borderRadius:10},
          {type:"primary",size:"large",label:"large",borderRadius:0},
          {type:"primary",size:"small",label:"small",borderRadius:10},
        ]},
        {label:"Disabled",common:{appearance:"A3",decoType:"C",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A3",decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A3",plain:true,decoType:"C"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Plain Disabled",common:{appearance:"A3",plain:true,decoType:"C",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

      ]},
      {label:"A3D",children:[
        {label:"Normal",common:{appearance:"A3",decoType:"D"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {type:"primary",label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Disabled",common:{appearance:"A3",decoType:"D",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A3",decoType:"D"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A3",plain:true,decoType:"D"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon"},
          {type:"primary",size:"large",label:"large"},
          {type:"primary",size:"small",label:"small"},
        ]},
        {label:"Plain Disabled",common:{appearance:"A3",plain:true,decoType:"D",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

      ]},
      {label:"A3E",children:[
        {label:"Normal",common:{appearance:"A3",decoType:"E"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {type:"primary",label:"Custom",customColor:$c.pul4,decoOffset:0},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoOffset:20},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:40},
          {type:"primary",size:"large",label:"large",decoOffset:2,decoThickness:6},
          {type:"primary",size:"small",label:"small",decoOffset:2,decoThickness:2},
        ]},
        {label:"Disabled",common:{appearance:"A3",decoType:"E",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A3",decoType:"E"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A3",plain:true,decoType:"E"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoOffset:8},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:8},
          {type:"primary",size:"large",label:"large",decoOffset:2},
          {type:"primary",size:"small",label:"small",decoOffset:2},
        ]},
        {label:"Plain Disabled",common:{appearance:"A3",plain:true,decoType:"E",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

      ]},
      {label:"A3F",children:[
        {label:"Normal",common:{appearance:"A3",decoType:"F"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",},
          {type:"primary",label:"Custom",customColor:$c.pul4,decoOffset:0},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoOffset:8},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:8},
          {type:"primary",size:"large",label:"large",decoOffset:2},
          {type:"primary",size:"small",label:"small",decoOffset:2},
        ]},
        {label:"Disabled",common:{appearance:"A3",decoType:"F",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"A3",decoType:"F"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},

        {label:"Plain Normal",common:{appearance:"A3",plain:true,decoType:"F",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
          {type:"divider"},
          {type:"default",icon:"tui-icon ti-star",label:"With icon",decoOffset:8},
          {type:"primary",icon:"tui-icon ti-star",label:"With icon",decoOffset:8},
          {type:"primary",size:"large",label:"large",decoOffset:2},
          {type:"primary",size:"small",label:"small",decoOffset:2},
        ]},
        {label:"Plain Disabled",common:{appearance:"A3",plain:true,decoType:"F",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis"},
          {label:"Custom",customColor:$c.pul4},
        ]},
      ]},
    ],
    B1:[
      {label:"B1A",children:[
        {label:"Normal",common:{appearance:"B1",decoType:"A",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {type:"primary",iconPosition:"end",label:"Custom",customColor:$c.pul4,decoOffset:0},
          {type:"divider"},
          {type:"primary",size:"large",label:"large",decoOffset:2,icon:null},
          {type:"primary",size:"small",label:"small",decoOffset:2,icon:"tui-icon ti-home"},
        ]},
        {label:"Disabled",common:{appearance:"B1",decoType:"A",icon:"tui-icon ti-home",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"B1",decoType:"A",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
        {label:"Plain Normal",common:{appearance:"B1",plain:true,decoType:"A",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",iconPosition:"end",},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
          {type:"divider"},
          {type:"primary",iconPosition:"end",size:"large",label:"large",decoOffset:2,icon:null},
          {type:"primary",iconPosition:"end",size:"small",label:"small",decoOffset:2,icon:null},
        ]},
        {label:"Plain Disabled",common:{appearance:"B1",plain:true,decoType:"A",icon:"tui-icon ti-home",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
      ]},
      {label:"B1B",children:[
        {label:"Normal",common:{appearance:"B1",decoType:"B",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {type:"primary",iconPosition:"end",label:"Custom",customColor:$c.pul4,decoOffset:0},
          {type:"divider"},
          {type:"primary",size:"large",label:"large",decoOffset:2,icon:null},
          {type:"primary",size:"small",label:"small",decoOffset:2,icon:"tui-icon ti-home"},
        ]},
        {label:"Disabled",common:{appearance:"B1",decoType:"B",icon:"tui-icon ti-home",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"B1",decoType:"B",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
        {label:"Plain Normal",common:{appearance:"B1",plain:true,decoType:"B",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",iconPosition:"end",},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
          {type:"divider"},
          {type:"primary",iconPosition:"end",size:"large",label:"large",decoOffset:2,icon:null},
          {type:"primary",iconPosition:"end",size:"small",label:"small",decoOffset:2,icon:null},
        ]},
        {label:"Plain Disabled",common:{appearance:"B1",plain:true,decoType:"B",icon:"tui-icon ti-home",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
      ]},
      {label:"B1C",children:[
        {label:"Normal",common:{appearance:"B1",decoType:"C",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {type:"primary",iconPosition:"end",label:"Custom",customColor:$c.pul4,decoOffset:0},
          {type:"divider"},
          {type:"primary",size:"large",label:"large",decoOffset:2,icon:null},
          {type:"primary",size:"small",label:"small",decoOffset:2,icon:null},
        ]},
        {label:"Disabled",common:{appearance:"B1",decoType:"C",icon:"tui-icon ti-home",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
        {label:"Active",className:"is-active",common:{appearance:"B1",decoType:"C",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
        {label:"Plain Normal",common:{appearance:"B1",plain:true,decoType:"C",icon:"tui-icon ti-home"},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger",},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
          {type:"divider"},
          {type:"primary",iconPosition:"end",size:"large",label:"large",decoOffset:2,icon:null},
          {type:"primary",iconPosition:"end",size:"small",label:"small",decoOffset:2,icon:null},
        ]},
        {label:"Plain Disabled",common:{appearance:"B1",plain:true,decoType:"C",icon:"tui-icon ti-home",disabled:true},children:[
          {type:"default"},
          {type:"invert"},
          {type:"focus"},
          {type:"info"},
          {type:"primary"},
          {type:"success"},
          {type:"warning"},
          {type:"danger"},
          {type:"emphasis",iconPosition:"end"},
          {label:"Custom",iconPosition:"end",customColor:$c.pul4},
        ]},
      ]},
    ],
  },


})

onMounted(() => {
})

</script>
<template>
  <div class="button-demo-wrap">
    <div class="operat-bar">
      
      <div class="form-group">
        <div class="label">外观</div>
        <TuiRadio v-bind="state.radioCfg" v-model="state.buttonApperAct" >
          <TuiRadioItem v-for="(item,index) in state.buttonApperOpt" :value="item">{{ item }}</TuiRadioItem> 
        </TuiRadio>
      </div>
      <div class="form-group">
        <div class="label">显示Active状态组</div>
        <TuiRadio v-bind="state.radioCfg" v-model="state.showActiveGroup" :options="state.boolOpt"/>
      </div>
    </div>
    <div class="demo-layout" @click="poptipEvent">
      <template v-for="(groupM,indexM) in state.groupObj[state.buttonApperAct]">
        <div class="group-title">{{ groupM.label }}</div>
        <div class="group">
          <template v-for="(groupS,indexS) in groupM.children">
            <template v-if="groupS.label!='Active'||state.showActiveGroup">
              <div class="group-sub-title">{{ groupS.label }}</div>
              <div class="group-sub">
                <template v-for="(btn,indexB) in groupS.children">
                  <TuiButton :class="groupS.className" v-if="btn.type!='divider'" v-bind="{...groupS.common,...btn}">{{ btn.label||btn.type }}</TuiButton>
                  <div class="divider" v-else></div>
                </template>
              </div>
            </template>
  
          </template>
          
        </div>

      </template>

      <template v-if="state.buttonApperAct=='Group'">
      
        <div class="group-title">Button Group</div>
        <div class="group btn-group">
          <TuiButtonGroup>
            <TuiButton type="primary">ButtonA</TuiButton>
            <TuiButton type="primary">ButtonB</TuiButton>
            <TuiButton type="primary">ButtonC</TuiButton>
          </TuiButtonGroup>

          <TuiButtonGroup>
            <TuiButton type="default">ButtonA</TuiButton>
            <TuiButton type="default">ButtonB</TuiButton>
            <TuiButton type="primary">ButtonC</TuiButton>
          </TuiButtonGroup>

          <TuiButtonGroup size="large">
            <TuiButton type="default">ButtonA</TuiButton>
            <TuiButton type="default">ButtonB</TuiButton>
            <TuiButton type="primary">ButtonC</TuiButton>
          </TuiButtonGroup>

          <TuiButtonGroup size="small">
            <TuiButton type="default">ButtonA</TuiButton>
            <TuiButton type="default">ButtonB</TuiButton>
            <TuiButton type="default">ButtonC</TuiButton>
          </TuiButtonGroup>

          <TuiButtonGroup>
            <TuiButton type="default">ButtonA</TuiButton>
            <TuiButton type="focus">ButtonA</TuiButton>
            <TuiButton type="info">ButtonB</TuiButton>
            <TuiButton type="primary">ButtonC</TuiButton>
            <TuiButton type="success">ButtonD</TuiButton>
            <TuiButton type="warning">ButtonE</TuiButton>
            <TuiButton type="danger">ButtonF</TuiButton>
            <TuiButton type="emphasis">ButtonF</TuiButton>
          </TuiButtonGroup>
          
          <TuiButtonGroup vertical>
            <TuiButton type="default">ButtonA</TuiButton>
            <TuiButton type="info">ButtonB</TuiButton>
            <TuiButton type="primary">ButtonC</TuiButton>
            <TuiButton type="success">ButtonD</TuiButton>
            <TuiButton type="warning">ButtonE</TuiButton>
            <TuiButton type="danger">ButtonF</TuiButton>
          </TuiButtonGroup>
          
          <TuiButtonGroup vertical>
            <TuiButton type="default">ButtonA</TuiButton>
            <TuiButton type="default">ButtonB</TuiButton>
            <TuiButton type="default">ButtonC</TuiButton>
          </TuiButtonGroup>

        </div>
        <div class="group-title">Button Group</div>
        <div class=" btn-group">
          <TuiButton type="primary">ButtonA</TuiButton>
          <TuiButton type="primary">ButtonB</TuiButton>
          <TuiButton type="primary">ButtonC</TuiButton>
        </div>
      </template>

    </div>
  </div>
</template>
<style lang="less">
.button-demo-wrap{ min-height:100%; width:1400px; margin:0 auto; padding:20px 20px 100px 20px; .por;
  .operat-bar{.flex(30px); padding:0 20px;
    .form-group{
      .label{margin:10px 0;}
    }
  }
  .demo-layout{ .flex(20px); padding:20px; flex-wrap: wrap; .por;
    .group-title{width: 100%; .bdb(var(--common-bd)); font-size: 18px; padding:10px 0; font-weight: bold;}
    .group{.flex(20px); flex-direction: column; margin:0 0 30px 0;
      &.btn-group{align-items: start;}
      .group-sub-title{}
      .group-sub{.flex; align-items: center;
        .divider{width: 2px; .bgc(var(--common-bg)); height:100%; margin:0 10px;}
      }
      
    }
  }
}
</style>
